# Generated by Django 5.1.5 on 2025-01-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_imgae_posts_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='Post',
        ),
    ]
