# Generated by Django 5.1.5 on 2025-01-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imgae',
            field=models.ImageField(upload_to='media'),
        ),
    ]
