# Generated by Django 5.1.5 on 2025-01-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posts_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='imgae',
            new_name='image',
        ),
    ]
